### ISSUE TITLE
snabb.co redirect to Github

### ISSUE THREAD

**Issue by lukego** [snabbco/snabb#1050] opened 2016-10-21 09:03 UTC
I have now transitioned the Snabb domain (http://snabb.co and http://www.snabb.co/) to redirect to our Github project page.  (Could take a little while to propagate.)

This is simply following through on the plan discussed over at https://github.com/snabbco/snabb/issues/738#issuecomment-180727157 i.e. for the Snabb name/trademark to refer to this open source project.

Previously the `snabb.co` website was my own professional  shopfront but I will recreate that later under a different brand.

I suppose the next step is to provide `@snabb.co` email aliases to any maintainers who would like one.

**Comment by wingo** [comment] 2016-10-21 09:30
Neat.  Thanks for being an amazing project technical lead and steward; you have made a really lovely virtual place to work :-)

**Comment by lukego** [comment] 2016-10-21 09:39
Thanks Andy :). 'Tis a pleasure to be hacking with you all!

**Comment by eugeneia** [comment] 2016-11-08 15:00
Closing because the issue is resolved.

**Closed by eugeneia** 2016-11-08 15:00 UTC
Labels: enhancement
